version: "3"
services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_KEY=AIzaSyD6F_haAYk4IN9MqMQPj0Tu3FTMT5SvB_E
      - REACT_APP_DATABASE_URL=https://hackideas-fe798-default-rtdb.firebaseio.com
